---
name: Continuous Integration

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8]

    steps:
      # checkout codebase
      - uses: actions/checkout@v2

      # install python
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # install python depedencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt;

      # run actual unit tests
      - name: Test with unittest
        run: |
          python -m unittest tests.test_root
