---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis
  namespace: twang0
data:
  master.conf: |
    bind 0.0.0.0
    protected-mode no
    requirepass thisisapassword
    port 6379
    tcp-backlog 511
    timeout 0
    tcp-keepalive 300
    daemonize no
    supervised no
    pidfile /var/run/redis_6379.pid
    loglevel notice
    logfile ""
  slave.conf:  
    slaveof redis-0.redis 6379  